### ISSUE TITLE
Fix requirements

### ISSUE THREAD

**Issue by lizgzil** [nestauk/dap_prinz_green_jobs#79]
On trying to run `python dap_prinz_green_jobs/pipeline/ojo_application/extract_green_measures.py --config_name "base" --test_n 10`
it fails with:
```
2023-10-09 17:33:05,670 - dap_prinz_green_jobs - INFO - Loading the model from s3://prinz-green-jobs/outputs/models/green_skill_classifier/green_skill_classifier_20230906.joblib
Traceback (most recent call last):
  File "dap_prinz_green_jobs/pipeline/ojo_application/extract_green_measures.py", line 88, in <module>
    green_skills_outputs = gm.get_skill_measures(job_advert=ojo_sample_raw)
  File "/Users/elizabethgallagher/Code/dap_prinz_green_jobs/dap_prinz_green_jobs/pipeline/green_measures/green_measures.py", line 141, in get_skill_measures
    prop_green_skills = self.sm.get_measures(
  File "/Users/elizabethgallagher/Code/dap_prinz_green_jobs/dap_prinz_green_jobs/pipeline/green_measures/skills/skill_measures_utils.py", line 442, in get_measures
    all_extracted_green_skills_dict = self.map_green_skills(
  File "/Users/elizabethgallagher/Code/dap_prinz_green_jobs/dap_prinz_green_jobs/pipeline/green_measures/skills/skill_measures_utils.py", line 302, in map_green_skills
    green_skills_classifier.load(
  File "/Users/elizabethgallagher/Code/dap_prinz_green_jobs/dap_prinz_green_jobs/pipeline/green_measures/skills/green_skill_classifier.py", line 407, in load
    self.model = joblib.load(f)
  File "/Users/elizabethgallagher/miniconda3/envs/dap_prinz_green_jobs/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 648, in load
    obj = _unpickle(fobj)
  File "/Users/elizabethgallagher/miniconda3/envs/dap_prinz_green_jobs/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/Users/elizabethgallagher/miniconda3/envs/dap_prinz_green_jobs/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/Users/elizabethgallagher/miniconda3/envs/dap_prinz_green_jobs/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 402, in load_build
    Unpickler.load_build(self)
  File "/Users/elizabethgallagher/miniconda3/envs/dap_prinz_green_jobs/lib/python3.8/pickle.py", line 1705, in load_build
    setstate(state)
  File "sklearn/tree/_tree.pyx", line 728, in sklearn.tree._tree.Tree.__setstate__
  File "sklearn/tree/_tree.pyx", line 1432, in sklearn.tree._tree._check_node_ndarray
ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
```

I think because the skills classifier was trained using an older sklearn it is incompatible with the new requirements. 

It may be best to train a new model with the new sklearn version.

Also `pytest` fails due to the new numpy version.

Also we should update ojd_daps_skills to be from the new release

**Comment by india-kerle** [comment]
this issue was addressed in a merged branch - closing
